-- ============================================================
-- DASHBOARD DE FORMACIÓN - FINNEGANS
-- Base de datos Supabase / PostgreSQL
--
-- Pegar todo en Supabase > SQL Editor > New query > Run
--
-- ⚠️ OJO: este script arranca con DROP TABLE. Si lo volvés a correr,
-- BORRA TODOS LOS DATOS que haya cargados. Mientras sean datos de
-- prueba no importa; cuando haya datos reales, no correrlo de nuevo.
-- ============================================================

-- ============================================================
-- DE DÓNDE SALE CADA TABLA (los 4 Excel de 'proyecto dashboard/excel')
-- ============================================================
--
-- 1) NominaConDatosFicticios_JulioSeptiembre.xlsx   -> empleados
--    Encabezados en la fila 1, columnas A..I:
--      Legajo | Correo | Nombre | Apellido | Señority | Sector |
--      Equipo General | Gerente | Fecha de ingreso
--    Detalles del archivo:
--      - Legajo es entero (6, 760).
--      - Señority viene como texto libre ("Señor"): la app lo normaliza
--        con Seniority.fromString y acá se guarda el valor del enum.
--      - Gerente es el NOMBRE del gerente ("Gerencia1 Gerente1"), no un
--        legajo, y puede venir "SIN INFO".
--      - Fecha de ingreso viene como número de serie de Excel (37165):
--        se convierte a date en la importación.
--
-- 2) MockMoodleCursosJulioSeptiembre.xlsx           -> cursos
--    Encabezados en la fila 2, columnas B..D (la A está vacía):
--      NombreCurso | TipoCurso | CargaHoraria
--    Detalles del archivo:
--      - NO trae ninguna columna de ID de curso. Por eso id_curso lo
--        genera la base y el id de Moodle va aparte, en id_moodle, para
--        cuando los cursos entren por la API de Moodle en vez del Excel.
--      - TipoCurso viene como texto ("Habilidades Blandas") y se guarda
--        normalizado al enum TipoCurso de la app.
--      - Los nombres traen espacios al final ("Any Monday "): se guardan
--        recortados, y el check de abajo lo obliga.
--
-- 3) Horas de Capacitacion Julio-Septiembre.xlsx    -> horas_capacitacion
--    Encabezados en la fila 1, columnas A..K:
--      Transaccionid | Numerolegajo | Fecha | Caso | Curso |
--      Descripcioncurso | Clasificacion | Proyecto | Proyectoitem |
--      Horastotales | Descripcion
--    Detalles del archivo:
--      - Transaccionid viene como "2174334.0": es el id de transacción
--        del CRM y es la clave para no duplicar.
--      - Fecha es número de serie de Excel (46275).
--      - Curso es el NOMBRE del curso, no un id: se busca en
--        cursos.nombre y se guarda cursos.id_curso. "Choras - 46" (Caso)
--        NO es el id del curso.
--      - Clasificacion puede venir vacía.
--
-- 4) EstadoFinalizacionCursos_JulioSeptiembre.xlsx  -> estado_cursos
--    Encabezados en la fila 2, columnas B..E:
--      ID Empleado | Nombre del Curso | ¿Finalizó el Curso? |
--      Fecha de finalización
--    Detalles del archivo:
--      - ID Empleado viene como "5.0" y es el legajo.
--      - ¿Finalizó el Curso? viene "Sí"/"No".
--      - Fecha de finalización es serie de Excel (46282) y está VACÍA
--        cuando no finalizó.
--      - Este archivo NO trae horas registradas ni carga estimada: las
--        horas se calculan sumando horas_capacitacion y la carga sale de
--        cursos.carga_horaria. No se guardan duplicadas acá.
--      - El período (ej. 2026-T3) no está en el archivo: lo define la
--        importación.
-- ============================================================

drop table if exists estado_cursos cascade;
drop table if exists horas_capacitacion cascade;
drop table if exists cursos cascade;
drop table if exists empleados cascade;
drop table if exists importaciones cascade;

-- ------------------------------------------------------------
-- Auditoría de los 4 Excel
-- ------------------------------------------------------------
create table importaciones (
    id bigint generated by default as identity primary key,
    tipo text not null check (
        tipo in ('NOMINA','CURSOS_LMS','HORAS_CAPACITACION','ESTADO_FINALIZACION')
    ),
    nombre_archivo text not null,
    fecha_importacion timestamptz not null default now(),
    estado text not null default 'PROCESANDO'
        check (estado in ('PROCESANDO','EXITOSA','ERROR')),
    registros_procesados integer not null default 0,
    registros_insertados integer not null default 0,
    registros_actualizados integer not null default 0,
    registros_desactivados integer not null default 0,
    registros_omitidos integer not null default 0,
    mensaje_error text
);

-- ------------------------------------------------------------
-- 01 - Nómina
-- ------------------------------------------------------------
create table empleados (
    legajo integer primary key,
    correo text not null unique,
    nombre text not null,
    apellido text not null default '',
    -- Valor del enum Seniority de la app, no el texto crudo del Excel.
    seniority text not null check (
        seniority in (
            'trainee','junior1','junior2','junior3',
            'semisenior1','semisenior2','semisenior3',
            'senior1','senior2','senior3','manager'
        )
    ),
    sector text not null default '',
    equipo_general text not null default '',
    gerente text,                       -- nombre del gerente, puede ser "SIN INFO"
    fecha_ingreso date,
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 02 - Cursos LMS
-- ------------------------------------------------------------
-- El Excel de cursos no trae ID, así que la clave interna la genera la
-- base (id_curso) y el id de Moodle vive en su propia columna. El nombre
-- es único porque es lo que usan los otros dos Excel para referirse a un
-- curso (definición funcional del cliente).
create table cursos (
    id_curso bigint generated by default as identity primary key,
    id_moodle bigint unique,            -- null cuando el curso entró por Excel
    nombre text not null unique check (nombre = btrim(nombre)),
    -- Valor del enum TipoCurso de la app.
    tipo text not null check (
        tipo in (
            'habilidadesDeNegocio','habilidadesBlandas',
            'libresExploracion','dictadoCapacitaciones'
        )
    ),
    carga_horaria numeric(8,2) not null default 0 check (carga_horaria >= 0),
    -- No están en el Excel de Moodle, pero sí en el modelo Curso de la app y en
    -- el Excel de carga manual de cursos.
    area_curso text not null default '',
    instructor_legajo text not null default '',
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 03 - Horas de capacitación CRM
-- ------------------------------------------------------------
create table horas_capacitacion (
    transaccion_id bigint primary key,
    legajo integer not null references empleados(legajo),
    curso_id bigint not null references cursos(id_curso),
    fecha date not null,
    caso text,                          -- "Choras - 46"
    descripcion_curso text,
    clasificacion text,
    proyecto text,
    proyecto_item text,
    horas_totales numeric(8,2) not null check (horas_totales >= 0),
    descripcion text,
    -- El Excel no trae esta columna: la app la deduce del Caso / Descripción al
    -- importar. Hay que guardarla porque todo el cálculo de cumplimiento
    -- distingue horas tomadas de horas dictadas, y si no queda acá no se puede
    -- reconstruir al leer.
    tipo text not null check (tipo in ('tomada','dictada')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 04 - Estado / finalización
-- ------------------------------------------------------------
-- La clave es legajo + curso, SIN período, igual que el modelo
-- CertificacionMoodle de la app: una finalización es acumulativa (el trigger de
-- abajo impide que un curso finalizado vuelva atrás), así que no hace falta una
-- fila por trimestre. El período queda como dato informativo de qué Excel trajo
-- la fila, porque el archivo no lo incluye y la app maneja mes/año, no
-- trimestres.
create table estado_cursos (
    legajo integer not null references empleados(legajo),
    curso_id bigint not null references cursos(id_curso),
    finalizo boolean not null,
    fecha_finalizacion date,
    periodo text check (periodo ~ '^[0-9]{4}-T[1-4]$'),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (legajo, curso_id),
    -- Si finalizó, tiene fecha: es lo que ya valida la app al importar.
    constraint finalizado_con_fecha check (not finalizo or fecha_finalizacion is not null)
);

-- Un curso que ya figuraba como finalizado no vuelve a "no finalizado"
-- cuando se importa un Excel posterior del mismo período.
create or replace function no_desfinalizar_curso()
returns trigger
language plpgsql
as $$
begin
    if old.finalizo and not new.finalizo then
        new.finalizo := old.finalizo;
        new.fecha_finalizacion := old.fecha_finalizacion;
    end if;
    return new;
end;
$$;

create trigger trg_estado_no_desfinalizar before update on estado_cursos
for each row execute function no_desfinalizar_curso();

-- ------------------------------------------------------------
-- Índices útiles para consultas de la aplicación
-- ------------------------------------------------------------
create index idx_empleados_equipo on empleados (equipo_general);
create index idx_empleados_sector on empleados (sector);
create index idx_empleados_activo on empleados (activo);
create index idx_cursos_activo on cursos (activo);
create index idx_horas_legajo on horas_capacitacion (legajo);
create index idx_horas_curso on horas_capacitacion (curso_id);
create index idx_horas_fecha on horas_capacitacion (fecha);
create index idx_estado_curso on estado_cursos (curso_id);
create index idx_estado_periodo on estado_cursos (periodo);

-- ------------------------------------------------------------
-- updated_at automático
-- ------------------------------------------------------------
create or replace function actualizar_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger trg_empleados_updated_at before update on empleados
for each row execute function actualizar_updated_at();

create trigger trg_cursos_updated_at before update on cursos
for each row execute function actualizar_updated_at();

create trigger trg_horas_updated_at before update on horas_capacitacion
for each row execute function actualizar_updated_at();

create trigger trg_estado_updated_at before update on estado_cursos
for each row execute function actualizar_updated_at();

-- ============================================================
-- RLS
-- ============================================================
alter table importaciones enable row level security;
alter table empleados enable row level security;
alter table cursos enable row level security;
alter table horas_capacitacion enable row level security;
alter table estado_cursos enable row level security;

-- La app importa los 4 Excel, así que necesita SELECT + INSERT + UPDATE.
--
-- NO hay políticas de DELETE en ninguna tabla: nada se borra físicamente. Lo
-- que desaparece de un Excel se da de baja con UPDATE activo = false (borrado
-- lógico) en empleados y cursos, y por eso alcanza con permitir update.
--
-- Se incluye 'anon' porque el login de la app todavía no pasa por Supabase
-- Auth. Nunca usar service_role desde Flutter.
--
-- ⚠️ RIESGO CONOCIDO, A CERRAR ANTES DE CARGAR DATOS REALES ⚠️
-- Con 'anon' habilitado para escribir, cualquiera que tenga la publishable key
-- (viaja dentro de la app) puede leer y sobrescribir la nómina entera: legajos,
-- correos, gerentes y equipos. Cuando el login use Supabase Auth, borrar 'anon'
-- de las políticas de abajo y dejar solo 'authenticated'.

create policy "lectura importaciones" on importaciones
for select to anon, authenticated using (true);
create policy "carga importaciones" on importaciones
for insert to anon, authenticated with check (true);
create policy "actualiza importaciones" on importaciones
for update to anon, authenticated using (true) with check (true);

create policy "lectura empleados" on empleados
for select to anon, authenticated using (true);
create policy "carga empleados" on empleados
for insert to anon, authenticated with check (true);
create policy "actualiza empleados" on empleados
for update to anon, authenticated using (true) with check (true);

create policy "lectura cursos" on cursos
for select to anon, authenticated using (true);
create policy "carga cursos" on cursos
for insert to anon, authenticated with check (true);
create policy "actualiza cursos" on cursos
for update to anon, authenticated using (true) with check (true);

create policy "lectura horas" on horas_capacitacion
for select to anon, authenticated using (true);
create policy "carga horas" on horas_capacitacion
for insert to anon, authenticated with check (true);
create policy "actualiza horas" on horas_capacitacion
for update to anon, authenticated using (true) with check (true);

create policy "lectura estado" on estado_cursos
for select to anon, authenticated using (true);
create policy "carga estado" on estado_cursos
for insert to anon, authenticated with check (true);
create policy "actualiza estado" on estado_cursos
for update to anon, authenticated using (true) with check (true);

-- ============================================================
-- Control: tiene que dar 0 / 0 / 0 / 0 / 0 (tablas creadas y vacías)
-- ============================================================
select
    (select count(*) from empleados) as empleados,
    (select count(*) from cursos) as cursos,
    (select count(*) from horas_capacitacion) as horas_capacitacion,
    (select count(*) from estado_cursos) as estado_cursos,
    (select count(*) from importaciones) as importaciones;
